- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bashrc_local_after:
    ~/.dotfiles_local: ''
    ~/.gitconfig_local:
    ~/.hgrc_local:
    ~/.jupyter/jupyter_notebook_config.py:
    ~/.shell_local_after:
    ~/.ssh/config: ssh/config
    ~/.zshrc_local_after:

- shell:
  - git update-submodules # after linking ~/.gitconfig
