- clean: ['~', '~/.config']

- link:
    ~/.config/terminator:
      create: true
      force: true
      path: config/terminator/
    ~/.dotfiles_local: ''
    ~/.gitconfig_local: gitconfig_local
    ~/.zshrc_local_after: zshrc_local_after
    ~/.zshrc_local_before: zshrc_local_before

- shell:
  - git update-submodules # after linking ~/.gitconfig
