- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.dotfiles_local: ''
    ~/.gitconfig_local:
    ~/.hgrc_local:
    ~/.bashrc_local_before:
    ~/.zshrc_local_after:

- shell:
  - git update-submodules # after linking ~/.gitconfig
