- clean: ['~']

- link:
    ~/.dotfiles_local: ''
    ~/.gitconfig_local: gitconfig_local
    ~/.zshrc_local_after: zshrc_local_after

- shell:
  - [git update-submodules, Installing/updating submodules]
