- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.dotfiles_local: ''
    ~/.gitconfig_local:
    ~/.hammerspoon:
    ~/.hgrc_local:
    ~/.vimrc_local:
    ~/.zshrc_local_after:
    ~/.zshrc_local_before:

- shell:
  - git update-submodules # after linking ~/.gitconfig
