language: generic
os: osx

sudo: false

before_script:
  - mkdir -p ~/dotfiles-install-dir
  - git clone https://github.com/anishathalye/dotfiles
  - HOME=~/dotfiles-install-dir dotfiles/install

script:
  - HOME=~/dotfiles-install-dir ./install
